# Generated by Django 6.0.1 on 2026-01-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_tag_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fee',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='course',
            name='studytime',
            field=models.IntegerField(default=65),
        ),
    ]
