# Generated by Django 6.0.1 on 2026-01-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_comment_course_like_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m'),
        ),
    ]
